version: '3'

services:

  backend:
    image: dockerdemo
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/myuser
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    deploy:
      mode: replicated
      replicas: 2

  frontend:
    image: dockerdemoweb
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    deploy:
      mode: replicated
      replicas: 2

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
    deploy:
      mode: global