version: '3'

services:

  backend:
    image: 172.23.219.26:5000/docker-demo:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/myuser
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    deploy:
      mode: replicated
      replicas: 1

  frontend:
    image: 172.23.219.26:5000/docker-demo-web:latest
    ports:
      - "4200:80"
    deploy:
      mode: replicated
      replicas: 1

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret