version: '3.8'

services:
  backend:
    image: 172.24.191.230:5000/dockerdemo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/myuser
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    deploy:
      replicas: 3

  frontend:
    image: 172.24.191.230:5000/dockerdemoweb
    ports:
      - "4200:80"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager