version: '3'

services:
  registry:
    image: registry:2
    networks:
      - traefik_proxy
    volumes:
      - registry_data:/var/lib/registry
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.regsitry.rule=Host(`registry.myapp.com`)"
        - "traefik.http.routers.registry.entrypoints=web"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"

networks:
  traefik_proxy:
    external: true
volumes:
  registry_data: