version: '3.8'

services:
  traefik:
    image: traefik:v3.6
    networks:
      - traefik_proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--entrypoints.web.address=:80"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.watch=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=traefik_proxy"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=INFO"
      - "--accesslog=true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`traefik.myapp.com`)"
        - "traefik.http.routers.dashboard.entrypoints=web"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"

networks:
  traefik_proxy:
    external: true