version: '3.8'

services:

  frontend:
    image: registry.myapp.com/dockerdemoweb
    networks:
      - traefik_proxy
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`myapp.local`)"
        - "traefik.http.routers.frontend.entrypoints=web"
        - "traefik.http.routers.frontend.priority=1"
        - "traefik.http.services.frontend.loadbalancer.server.port=80"
        - "autoscaler.enabled=true"
        - "autoscaler.target_rps_per_replica=3"
        - "autoscaler.max_replicas=10"
        - "autoscaler.max_step_up=2"
        - "autoscaler.metric_service=frontend@swarm"

  backend:
    image: registry.myapp.com/dockerdemo
    networks:
      - traefik_proxy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/myuser
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`myapp.local`) && PathPrefix(`/api`)"
        - "traefik.http.routers.backend.entrypoints=web"
        - "traefik.http.routers.backend.priority=10"
        - "traefik.http.services.backend.loadbalancer.server.port=8080"
        - "autoscaler.enabled=true"
        - "autoscaler.target_rps_per_replica=.10"
        - "autoscaler.max_replicas=10"
        - "autoscaler.max_step_up=2"
        - "autoscaler.metric_service=backend@swarm"


  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    networks:
      - traefik_proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  autoscaler:
    image: dockerdemo-autoscaler:latest
    networks:
      - traefik_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      #force unbuffered Python logs in Docker.
      PYTHONUNBUFFERED: "1"
      TRAEFIK_METRICS_URL: http://traefik_traefik:8082/metrics
      POLL_SECONDS: "30"
      DRY_RUN: "false"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  traefik_proxy:
    external: true
