version: '3.8'

services:

  activemq:
    image: apache/activemq-classic:5.18.6
    networks:
      - traefik_proxy
    volumes:
      - activemq_data:/opt/apache-activemq/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.activemq.rule=Host(`activemq.myapp.com`)"
        - "traefik.http.routers.activemq.entrypoints=web"
        - "traefik.http.services.activemq.loadbalancer.server.port=8161"

networks:
  traefik_proxy:
    external: true

volumes:
  activemq_data:
