version: '3.8'

services:

  translator:
    image: registry.myapp.com/translator
    hostname: translator-svc
    networks:
      traefik_proxy:
        aliases:
          - translator-svc
    environment:
      LIBRETRANSLATE_URL: https://libretranslate.com/translate
      OTEL_SERVICE_NAME: translator-service
      OTEL_RESOURCE_ATTRIBUTES: "service.namespace=myapp,deployment.environment=production,host.name=translator-service"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-agent:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_INSTRUMENTATION_MICROMETER_ENABLED: "true"
      OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED: "true"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  traefik_proxy:
    external: true
